import { PROTOCOL_VERSION, type RuntimeMessage } from "../shared/types";
let stream: MediaStream | null = null; let context: AudioContext | null = null; let socket: WebSocket | null = null; let generation = 0; let paused = true; let playbackRate = 1; let anchorMedia = 0; let anchorContext = 0; let framesSent = 0;
const notify = (state: "idle" | "capturing" | "error", detail?: string) => chrome.runtime.sendMessage({ type: "CAPTURE_STATE", state, detail, bufferedAudioSeconds: framesSent / 16000 } satisfies RuntimeMessage).catch(() => undefined);
function resample(input: Float32Array, inputRate: number) { const ratio = inputRate / 16000; const output = new Int16Array(Math.floor(input.length / ratio)); for (let i = 0; i < output.length; i += 1) { const sample = Math.max(-1, Math.min(1, input[Math.floor(i * ratio)] ?? 0)); output[i] = sample < 0 ? sample * 0x8000 : sample * 0x7fff; } return output; }
async function stop() { stream?.getTracks().forEach((track) => track.stop()); stream = null; socket?.close(); socket = null; if (context) await context.close(); context = null; framesSent = 0; await notify("idle"); }
async function start(streamId: string, sessionId: string) {
  await stop(); stream = await navigator.mediaDevices.getUserMedia({ audio: { mandatory: { chromeMediaSource: "tab", chromeMediaSourceId: streamId } } as MediaTrackConstraints, video: false });
  context = new AudioContext(); await context.audioWorklet.addModule(chrome.runtime.getURL("audio-worklet.js")); const source = context.createMediaStreamSource(stream); const worklet = new AudioWorkletNode(context, "cinenihongo-processor"); const silent = context.createGain(); silent.gain.value = 0;
  source.connect(context.destination); source.connect(worklet); worklet.connect(silent); silent.connect(context.destination);
  socket = new WebSocket(`ws://127.0.0.1:8765/api/v1/sessions/${sessionId}/stream`); socket.binaryType = "arraybuffer";
  await new Promise<void>((resolve, reject) => { const timeout = setTimeout(() => reject(new Error("WebSocket handshake timed out")), 5000); socket!.onopen = () => socket!.send(JSON.stringify({ type: "handshake", protocolVersion: PROTOCOL_VERSION })); socket!.onerror = () => { clearTimeout(timeout); reject(new Error("WebSocket connection failed")); }; socket!.onmessage = (event) => { if (typeof event.data !== "string") return; const msg = JSON.parse(event.data); if (msg.type === "ready") { clearTimeout(timeout); resolve(); void notify("capturing"); } else if (msg.type === "result" && msg.result) chrome.runtime.sendMessage({ type: "ALIGNED_RESULT", result: msg.result } as RuntimeMessage); else if (msg.type === "error") void notify("error", msg.detail); }; });
  worklet.port.onmessage = ({ data }: MessageEvent<Float32Array>) => { if (!socket || socket.readyState !== WebSocket.OPEN || paused || !context) return; const pcm = resample(data, context.sampleRate); const mediaStart = anchorMedia + (context.currentTime - anchorContext) * playbackRate; const mediaEnd = mediaStart + pcm.length / 16000 * playbackRate; socket.send(JSON.stringify({ type: "audio", generation, mediaStart, mediaEnd, sampleRate: 16000, frames: pcm.length })); socket.send(pcm.buffer.slice(pcm.byteOffset, pcm.byteOffset + pcm.byteLength) as ArrayBuffer); framesSent += pcm.length; if (framesSent % 16000 < pcm.length) void notify("capturing"); };
}
chrome.runtime.onMessage.addListener((message: RuntimeMessage, _sender, respond) => {
  if (message.type === "OFFSCREEN_START") { start(message.streamId, message.sessionId).then(() => respond({ ok: true })).catch((error) => { void stop(); respond({ ok: false, error: String(error) }); }); return true; }
  if (message.type === "OFFSCREEN_STOP") { stop().then(() => respond({ ok: true })); return true; }
  if (message.type === "OFFSCREEN_SYNC" && context) { const expected = anchorMedia + (context.currentTime - anchorContext) * playbackRate; if (message.discontinuity || message.generation !== generation || message.paused !== paused || Math.abs(expected - message.mediaTime) > .4) { anchorMedia = message.mediaTime; anchorContext = context.currentTime; } generation = message.generation; paused = message.paused; playbackRate = message.playbackRate; respond({ ok: true }); }
});
